"""removed email from user model

Revision ID: 80d4586e8f91
Revises: c9876d1bc6b1
Create Date: 2026-01-10 16:03:32.066477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80d4586e8f91'
down_revision = 'c9876d1bc6b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_token'))
        batch_op.drop_column('email')
        batch_op.drop_column('token')
        batch_op.drop_column('token_expiration')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_expiration', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('token', sa.VARCHAR(length=32), nullable=True))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=128), nullable=False))
        batch_op.create_index(batch_op.f('ix_users_token'), ['token'], unique=1)

    # ### end Alembic commands ###
